### ISSUE TITLE
New metric request - % meta version 1.0

### ISSUE THREAD

**Issue by Eunice-Son** [brain-image-library/py-brain-inventory#20]
## Metric request

**Proposed Statistic/Metric**: I want to add a function that returns the percent of meta version 1.0 from the whole datasets

**Justification**: It would help us view the proportion of meta version 1.0 as there are various versions present 

## Implementation Details

**Data Source**: The information needed to compute the statistic should come from this file `https://download.brainimagelibrary.org/inventory/daily/reports/today.json` or any file(s) listed in `today.json`.

**Calculation Method**: dividing the number of meta version 1.0 over all datasets 

**Expected Output**: an integer 

## Additional Information

**Stakeholders**: all (data curators, project managers, scientists, etc)

**Viz**: text/possibly pie chart 

**Impact**: It will facilitate the data analysis of different versions and help the stakeholders' understanding of them. This might facilitate the possible extension of datasets in the future. 

**Contributor**: @Eunice-Son 

## Checklist

- [ ] I have reviewed the existing documentation to ensure the proposed statistic aligns with the scope and purpose.
- [ ] I have provided sufficient details about the proposed statistic, including its calculation method and expected output.
- [ ] I have referenced relevant documentation or resources that support the addition of the new statistic.
- [ ] I have considered the potential impact and benefits of adding this statistic to the dataset.
- [ ] I am willing to collaborate and work on implementing this new statistic, or I am seeking collaboration from others.
